### PR TITLE
Update

### PR DESCRIPTION
**Pull request by jdoconnor**
There's a lot here, as our guide was forked 3 years ago

### CODE REVIEW

**Comment by levity** [comment]
:cool:

**Comment by tdumitrescu** [comment]
r4d

**Comment by azach** [comment]
lolol

**Comment by ulfmagnetics** [comment]
:palm_tree: :palm_tree: :palm_tree:

**Comment by levity** [comment]
:ghost:

**Comment by tdumitrescu** [comment]
:cat:

**Comment by slpsys** [comment]
glad we're *finally* rolling back the clock to 2012

**Pull request closed without merging**
